### ISSUE TITLE
File Validation for upload.js

### ISSUE THREAD

**Issue by AaronGulman** [dwacochan/MEAN-Chat#1]
Hi !

I would like to suggest introducing some type of a file validation for your server side `upload.js` . 
I think you might find it relevant since without any type of a validation there , users could potentially upload malicious files,hence you should consider restricting uploads to certain file types.

Great job ,by the way !

**Comment by dwacochan** [comment]
Thank you, Aaron, for pointing out this detail I overlooked. I really appreciate the heads-up!
